name: phonedekho
description: E-Commrs platform for mobiles.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc:
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  badges: ^3.1.1 #cart count
  carousel_slider: ^4.2.1 #carousel_images: slider
  dotted_border: ^2.0.0+3 #dotted border for add product
  file_picker: ^5.3.2 #file picking for add product
  cloudinary_public: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
